version: '3'

services:
  next-app:
    container_name: nextjs-faro
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3700:3000
    networks:
        - local_grafananet
networks:
  local_grafananet:
    external: true